#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "thecalculaterspin"
version = "0.1.0"
authors = ["Uffe Hansen <uffe.hansen@gmail.com>"]
description = "HTTP API for the Scientific Calculator WASM component"

[[trigger.http]]
route = "/..."
component = "thecalculaterspin"

[component.thecalculaterspin]
source = "thecalculaterspin-composed.wasm"
allowed_outbound_hosts = []
[component.thecalculaterspin.build]
command = "cargo build --target wasm32-wasip2 --release && wac plug --plug ../the-calculater/the-calculater.wasm target/wasm32-wasip2/release/thecalculaterspin.wasm -o thecalculaterspin-composed.wasm"
watch = ["src/**/*.rs", "Cargo.toml"]
